-- liquibase formatted sql

-- changeset evgen:1
CREATE TABLE users (
                       id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       first_name VARCHAR(255) NULL,
                       last_name VARCHAR(255) NULL,
                       phone VARCHAR(12) NULL,
                       role INTEGER NULL,
                       image TEXT NULL,
                       password VARCHAR(100) NOT NULL,
                       ads INTEGER NULL,
                       comments INTEGER NULL,
                       PRIMARY KEY (id)
                    );

-- changeset evgen:2
CREATE TABLE ad (
                    pk INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    author_id INTEGER NOT NULL,
                    image TEXT NULL,
                    price INTEGER NULL,
                    title VARCHAR(255) NULL,
                    description TEXT NULL,
                    PRIMARY KEY (pk),
                    FOREIGN KEY (author_id) REFERENCES users(id)
                );

-- changeset evgen:3
CREATE TABLE comment (
                         pk INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         author_id INTEGER NULL,
                         author_image TEXT NULL,
                         author_first_name VARCHAR(255) NULL,
                         created_at BIGINT NULL,
                         text TEXT NULL,
                         users_id INTEGER NULL,
                         ad_pk INTEGER NOT NULL,
                         PRIMARY KEY (pk),
                         FOREIGN KEY (users_id) REFERENCES users(id),
                         FOREIGN KEY (ad_pk) REFERENCES ad(pk)
                    );